spring.application.name=url-shortener
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortener
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380

# JWT
jwt.secret=urlShortenerSecretKeyForJWTTokenGenerationMustBe256BitsLong123456
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.urlshortener=DEBUG
